project_name: dnsexit
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
    binary: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
  extra_files:
    - glob: ./dist/{{ .ProjectName }}_darwin_amd64/*
    - glob: ./dist/{{ .ProjectName }}_linux_amd64/*
snapshot:
  name_template: '{{ incpatch .Version }}-rc_{{ .ShortCommit }}'
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - 'test'
      - 'correct'
      - '^WIP'
      - 'README'
      - 'gitlab'
release:
  extra_files:
    - glob: ./dist/{{ .ProjectName }}_darwin_amd64/*
    - glob: ./dist/{{ .ProjectName }}_linux_amd64/*
brews:
  - name: '{{ .ProjectName }}'
    tap:
        owner: christiantragesser
        name: homebrew-tap
    folder: Formula
    commit_author:
        name: goreleaserbot
        email: release-bot@evoen.net
    homepage: "https://github.com/christianTragesser/dnsexit-ip-update"
    description: "A DNSExit dynamic ip address DNS client"
    license: "MIT"
    post_install: |
      system "rm -f /usr/local/bin/dnsexit || true"
      system "ln -s #{bin}/dnsexit-* /usr/local/bin/dnsexit"
    test: |
        system "#{bin}/dnsexit version"