name: CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'dnsexit/**'
      - 'pkg/**'
    tags-ignore:
      - '**'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run linter
        run: golangci-lint run

  unit-test:
    runs-on: ubuntu-latest
    container: golang:bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        run: go test -v --cover ./dnsexit

  publish:
    needs: [ lint, unit-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c1-8 )"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: "./pkg/Dockerfile"
          push: true
          tags: christiantragesser/dnsexit-ip-update:${{ steps.vars.outputs.sha_short }},christiantragesser/dnsexit-ip-update:latest