name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master", "golang-client" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: registry.gitlab.com/christiantragesser/gitlab-ci-templates/intermodal:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          /kaniko/executor
          --context dnsexit
          --dockerfile pkg/Dockerfile
          --destination christiantragesser/intermodal:latest
          --skip-unused-stages
          --target test
          ${KANIKO_ADDITIONAL_ARGS}