name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master", "golang-client" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run linter
        run: golangci-lint run
  test:
    runs-on: ubuntu-latest
    container: golang:stretch 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run unit tests
        run: go test -v --cover ./dnsexit