name: CI

on:
  push:
    branches: [ "master", "golang-client" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run linter
        run: golangci-lint run

  unit-test:
    runs-on: ubuntu-latest
    container: golang:stretch 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run unit tests
        run: go test -v --cover ./dnsexit
  
  build:
    needs: [ lint, unit-test ]
    runs-on: ubuntu-latest
    container: registry.gitlab.com/christiantragesser/gitlab-ci-templates/intermodal:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: binary builds
        run: goreleaser build --snapshot
      
      - uses: actions/cache@v2
        id: app-binaries
        with:
          path: ./dist/dnsexit_linux_amd64_v1/
          key: dnsexit-linux-amd64
  
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: app-binaries
        with:
          path: ./dist/dnsexit_linux_amd64_v1/
          key: dnsexit-linux-amd64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: "./pkg/Dockerfile"
          push: true
          tags: christiantragesser/dnsexit-ip-update:latest