name: Release

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  binary-release:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/christiantragesser/gitlab-ci-templates/intermodal:github
    env:
      GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Binary releases
        run: |
          /usr/bin/git config --global --add safe.directory /__w/dnsexit-ip-update/dnsexit-ip-update
          goreleaser release
  
  container-image-release:
    needs: binary-release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: "./pkg/Dockerfile"
          push: true
          tags: christiantragesser/dnsexit-ip-update:${{ github.ref_name }},christiantragesser/dnsexit-ip-update:latest